services:
  db:
    image: postgres
    container_name: tasks-db
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: hfa
      POSTGRES_PASSWORD: changeinprod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-net

  backend:
    build:
      context: ./tasks-backend # Dockerfile located in tasks-backend folder
    container_name: tasks-backend
    depends_on:
      - db # Ensures DB is available before the app starts
    ports:
      - "8080:8080" # Exposes backend on port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasks # DB connection URL for Spring
      SPRING_DATASOURCE_USERNAME: hfa
      SPRING_DATASOURCE_PASSWORD: changeinprod
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - spring-net # Connects to the custom network

  frontend:
    build:
      context: ./tasks-frontend
    container_name: tasks-frontend
    depends_on:
      - backend # Ensures frontend starts after backend
    ports:
      - "3000:3000" # Exposes frontend on port 3000
    environment:
      API_URL: http://tasks-backend:8080 # Frontend will communicate with the backend API
    networks:
      - spring-net

volumes:
  postgres-data:

networks:
  spring-net:
