name: Build and Run Docker App

on:
  push:
    branches: [main]
  #schedule:
  #  - cron: "0 3 * * *" # every day at 3AM UTC

#Jobs run in parallel
jobs:
  #cleanup:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Run Cleanup
  #      run: python scripts/cleanlogs.py

  build:
    #needs: cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Docker versions
        run: |
          docker --version
          docker compose version
          which docker
          ls -la /usr/bin/docker*

      #- name: Make deploy.sh executable and run it
      #  run: |
      #    chmod +x scripts/deploy.sh
      #    ./scripts/deploy.sh
      - name: Build and run app
        run: |
          docker compose build
          docker compose up -d
      - name: Check if containers are running
        run: docker ps
